apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-pkg-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: build-pkg
  volumes:
  - name: git-secret-vol
  secret:
    secretName: git-token
  arguments:
    parameters:
    - name: message
      value: "Msg from ketan"
  templates:
  - name: build-pkg
    inputs:
      parameters:
      - name: message
    env:
    - name: USER
    valueFrom:
      secretKeyRef:
        name: git-token
        key: username
    - name: TOKEN
    valueFrom:
      secretKeyRef:
        name: git-token
        key: password
    script:
      image: ubuntu:18.04
      command: [bash]
      source: |
        cat /etc/os-release
        echo $USER
        echo $TOKEN
        #git clone https://github.ibm.com/open-ce/numactl-feedstock.git
        echo {{workflow.name}}
        echo {{workflow.namespace}}
        echo {{workflow.serviceAccountName}}
        echo {{workflow.uid}}
