apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: secret-example-
spec:
  entrypoint: whalesay
  volumes:
  - name: my-secret-vol
    secret:
      secretName: git-token   
  templates:
  - name: whalesay
    container:
      image: ubuntu:18.04
      command: [sh, -c]
      args: ['
        echo "secret from env: $USER $PASSWD" ;
        echo "secret from file: `cat /secret/mountpath/mypassword`"
      ']
      env:
      - name: USER  # name of env var
        valueFrom:
          secretKeyRef:
            name: git-token     # name of an existing k8s secret
            key: username     # 'key' subcomponent of the secret
      - name: PASSWD  # name of env var
        valueFrom:
          secretKeyRef:
            name: git-token     # name of an existing k8s secret
            key: password     # 'key' subcomponent of the secret
      volumeMounts:
      - name: secret-vol     # mount file containing secret at /secret/mountpath
        mountPath: "/secret/mountpath"
